name: It's Joel, Online

title: Joel, Online

kramdown:
  auto_ids: true

collections:
  projects:
    output: true

highlighter: rouge

sass:
  sass_dir: _sass

colors:
  background: rgb(250, 242, 231)
  body: black
  shadow: gray

plugins:
  - jekyll-sitemap
  - jemoji
  